# Generated by Django 3.2.13 on 2022-05-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
    ]
